- lib/puppet-lint/tasks/puppet-lint.rb
Else rake throws a RuntimeError, "Don't know how to build task 'lint'"
---
Since 0f2e2db / #331 / #332, requiring the file that loads the initial lint rake task throws the following error:
<pre>$ irb -Ilib -rpuppet-lint/tasks/puppet-lint
/home/dcleal/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task_manager.rb:49:in `[]': Don't know how to build task 'lint' (RuntimeError)
from /home/dcleal/.rvm/gems/ruby-2.0.0-p247@global/gems/rake-10.1.0/lib/rake/task.rb:348:in `[]'
from /home/dcleal/code/puppet/puppet-lint/lib/puppet-lint/tasks/puppet-lint.rb:54:in `define'
from /home/dcleal/code/puppet/puppet-lint/lib/puppet-lint/tasks/puppet-lint.rb:45:in `initialize'
from /home/dcleal/code/puppet/puppet-lint/lib/puppet-lint/tasks/puppet-lint.rb:87:in `new'
from …
> Only clear task if it's already defined

- lib/puppet-lint/plugins/check_classes.rb
- spec/puppet-lint/plugins/check_classes/variable_scope_spec.rb
For more information on $facts and $trusted see https://docs.puppetlabs.com/puppet/latest/reference/lang_facts_and_builtin_vars.html
Hopefully this meets with your approval, if not please let me know how this can be done and I will revise it :)
Thanks
-Richard
> rpearce: Allow the use of facts[] and trusted[] as per Puppet 3.5+

- lib/puppet-lint/lexer.rb
- lib/puppet-lint/lexer/token.rb
- lib/puppet-lint/plugins/check_comments.rb
- spec/puppet-lint/lexer_spec.rb
Spent a bit of time trying to find a sane way of reconstructing `:MLCOMMENT` tokens to fix #373 but it ended up just being a mess of corner cases as it was too easy to break with slight formatting changes.  Decided it was saner to just store the raw value to use when rendering them back into manifest form while retaining the stripped down value to use when converting to `:COMMENT` tokens.
Closes #373
> Save the raw value of MLCOMMENT tokens to use when rendering back to a manifest

- lib/puppet-lint/plugins/check_whitespace.rb
- spec/puppet-lint/plugins/check_whitespace/trailing_whitespace_spec.rb
Due to how the tokeniser works, whitespace following a `:NEWLINE` token has a token type of `:INDENT` rather than `:WHITESPACE` (for easier logic in some checks). The `trailing_newline` check needs to check for these tokens too.
Closes #359
> Detect trailing whitespace on lines with no code

- lib/puppet-lint/plugins/check_whitespace.rb
- spec/puppet-lint/plugins/check_whitespace/arrow_alignment_spec.rb
> Don't warn for arrow alignment for single-element hashes

- lib/puppet-lint/plugins/check_strings.rb
- spec/fixtures/test/manifests/url_interpolation.pp
- spec/puppet-lint/plugins/check_strings/puppet_url_without_modules_spec.rb
Currently, it misses all but 'test1' from the url_interpolation.pp file below. This corrects that.
> Fix puppet:// url check to catch double quoted strings

- lib/puppet-lint/optparser.rb
Add a --load-from-puppet MODULEPATH option.
Puppet-lint searches for lib/puppet-lint/plugins
directories in each module of the passed MODULEPATH.
> Load puppet-lint plugins from Puppet modules

- lib/puppet-lint.rb
This is an alternate solution to rodjek/puppet-lint#392.
This also fixes dealing with empty files in all plugins. So perhaps this is a better solution.
> Skip checks on empty files

- lib/puppet-lint/tasks/puppet-lint.rb
I noticed that ignore_paths is not working when set as documented.
```
PuppetLint.configuration.ignore_paths = ["spec/**/*.pp", "pkg/**/*.pp"]
```
Simply because @ignore_paths is defined on task creation.
There are two examples, the one configuring the tasks works of course,
the second like above doesn't work without my addition.
Make sense?
> Get ignore_paths from the configuration

- lib/puppet-lint/plugins/check_conditionals.rb
- spec/puppet-lint/plugins/check_conditionals/case_without_default_spec.rb
Previously, it was possible to miss case statements without a default case when there were nested case statements in the mix. This came up when I was answering this question on ask.puppetlabs.com:
http://ask.puppetlabs.com/question/14669/puppet-rspec-fails-when-testing-against-none-standard-type/
I was planning to suggest running puppet-lint to catch the error, but when I tried it didn't seem to be working - it didn't notice the case statement without a default, because there was another case statement enclosed that did have one.
This commit fixes that problem by ensuring that default cases are matched up with their owning case statement, and not with any other case statements that might exist within the scope.
> Nested cases

- lib/puppet-lint/plugins/check_classes.rb
- spec/puppet-lint/plugins/check_classes/names_containing_dash_spec.rb
See #289  
closes #289 
Instead of differentiating between module/class names and defines, treat hyphens as an error in both
@rodjek Wdyt? May be it does not make sense to treat defines differently after all
> Alternative to #289: :error on either class names and defines

- lib/puppet-lint/plugins/check_whitespace.rb
> Fix arrow_alignment check to not raise exception when line isn't indented

- README.md
- lib/puppet-lint/plugins/check_whitespace.rb
- spec/puppet-lint/plugins/check_whitespace/140chars_spec.rb
Per the Puppet 3.7+ Style Guide (http://docs.puppetlabs.com/guides/style_guide.html#spacing-indentation-and-whitespace) - Module manifests should not exceed a 140-character line width. I've updated the whitespace plugin, its test, and the readme to reflect this.
> Changed character width to 140.

- lib/puppet-lint/plugins/check_classes.rb
- spec/puppet-lint/plugins/check_classes/variable_scope_spec.rb
Strip subscripts from variable names when checking for future parser
scoped variables.
Update future scope spec test to ensure subscripted references pass.
> Fix issue #450: block-local variables aren't recognized with subscripts

- .gitignore
- CHANGELOG.md
The initial contents address the breaking change in 2.0.0.
Gitignore now properly ignores all contents of `vendor/`
> Add a CHANGELOG

- lib/puppet-lint.rb
- spec/puppet-lint_spec.rb
When you pass an empty file (of zero bytes) to the `puppet-lint --fix` command,
puppet-lint generates a strange file with its content being `[]`, which cannot be parsed by Puppet.
This patch fixes this problem.
> Fix handling of empty code

- lib/puppet-lint/plugins/check_resources.rb
Fix for issue #341
I tested with:
```
class double_arrow {
file {'/etc/foo': ensure=>'/usr/share/foo' }
}
class double_arrow_other {
file {'/etc/foo': ensure =>'/usr/share/foo' }
}
class double_arrow_correct{
file {'/etc/foo':
ensure=>'/usr/share/foo'
}
}
```
Gets turned into:
```
class double_arrow {
file {'/etc/foo': ensure =>symlink,
target => '/usr/share/foo' }
}
class double_arrow_other {
file {'/etc/foo': ensure =>symlink,
target => '/usr/share/foo' }
}
class double_arrow_correct{
file {'/etc/foo':
ensure =>symlink,
target => '/usr/share/foo'
}
}
```
Spacing is still off a bit.  however the => => is gone.
> Fix double arrow issue when adding target to ensure symlink

- lib/puppet-lint/plugins/check_classes.rb
- spec/puppet-lint/plugins/check_classes/parameter_order_spec.rb
The current parameter order check only checks for defined types and was not checking class types. I think this somehow got unexpectedly remove with the code cleanup.
> Parameters ordering was only checked on defined types

- lib/puppet-lint/plugins/check_variables.rb
- spec/puppet-lint/plugins/check_variables/variable_is_lowercase_spec.rb
This is a new check to ensure that all variables are lowercase, based on the [most recent release changes.](https://github.com/puppetlabs/puppet-docs/commit/3ea1e03afea45cc60381e218245415bfba8c5c5e#diff-b59ced089c60377b666c1c1fb5b1e1b8R737)
> Check that variables are lowercase

- lib/puppet-lint/plugins/check_variables.rb
After merging #418, these warnings started appearing:
```
$ bundle exec puppet-lint --version
/home/rnelson0/git/puppet-lint/lib/puppet-lint/plugins/check_variables.rb:22: warning: already initialized constant VARIABLE_TYPES
/home/rnelson0/git/puppet-lint/lib/puppet-lint/plugins/check_variables.rb:4: warning: previous definition of VARIABLE_TYPES was here
puppet-lint 2.0.0
```
The new token constants for each check had the same name, and have now been given unique names.
> Regression from 418: duplicate constant

- lib/puppet-lint/lexer.rb
- spec/puppet-lint/lexer_spec.rb
fixes #452
Puppet 4 data types such as Parameters and Regexp allow one to use
regexp as a parameter.
> Allow regex params for puppet data types

- lib/puppet-lint/plugins/check_resources.rb
- spec/puppet-lint/plugins/check_resources/ensure_first_param_spec.rb
"ensure" should be the first attribute for resources that contain that attribute (Guide 9.3). In other resource types, it is a hash key and can come in any order.
> (GH410) Limit ensure_first_param check to certain resources

- lib/puppet-lint/tasks/puppet-lint.rb
README says you can configure a Rake task as
```rb
PuppetLint::RakeTask.new :lint do |config|
config.fix = true
end
```
to enable automatic fixing, but this actually doesn't work now, since writing back fixed manifests is implemented in `lib/puppet-lint/bin.rb` and this code is not called when puppet-lint is invoked as a rake task.
This patch is to fix this problem by making the Rake task write back the fixed manifest to the source file when any problem is found.
> Support automatic fixing in Rake task as described in README

- lib/puppet-lint/plugins/check_classes.rb
- spec/puppet-lint/plugins/check_classes/class_inherits_from_params_class_spec.rb
This reinstates the check removed in #510, but disables it. This will make it less likely that existing tooling will break on this change.
When #495 is merged, it can be re-enabled on invocation.
> Make params disabled

- lib/puppet-lint/optparser.rb
- lib/puppet-lint/plugins/check_whitespace.rb
- spec/puppet-lint/bin_spec.rb
- spec/puppet-lint/plugins/check_whitespace/80chars_spec.rb
This commit adds back an 80chars check, but disables it by default. To
do this, I also added the ability to re-enable checks that have been
disabled.
The spec is failing and I don't have time to fix it just now, but it
works when called from the command line. I'll come back to it if nobody
else picks this up.
A better solution than calling `Puppet.configuration` to disable a check
like I did might be to extend the `new_check` method. That's not
orthagonal to this PR though.
Supercedes #488
Fixes #484
> This adds a disabled-by-default 80chars check

- lib/puppet-lint/checks.rb
In #366, an issue was identified where tab indents may cause a negative argument error when creating the new indent for alignment. This occurred because the problem was logged prior to the tab being replaced with two spaces, which changed the alignment.
The fix is to, when `--fix` is passed, run each plugin's  immediately after it's  method. This ensures that problems are fixed immediately, so the next check runs against the updated code.
This may resolve some of the other issues with `--fix` as well.
> (GH366) Arrow Alignment fix crashes with tabs

- puppet-lint.gemspec
Without this patch, upgrades to json will not work on Ruby 1.8.7 and
1.9.3 and automated testing will fail.
> Continue supporting Ruby < 2

- lib/puppet-lint/plugins/check_classes.rb
Per https://tickets.puppetlabs.com/browse/DOCUMENT-560, these variables are protected and always top level and thus do not need the colons.
> New additions of protected variables

- .travis.yml
- CHANGELOG.md
- Gemfile
- README.md
- lib/puppet-lint/version.rb
- puppet-lint.gemspec
2.0.1 includes a lot of post 2.0.0 cleanup and fixes. In addition, **Ruby 1.8.7 support is now deprecated**, though it will not be removed until the next MAJOR version release.
> Release 2.0.1

- README.md
The current README doesn't show off what puppet lint has developed into enough, and it's wide flexibility as far as how one can set or run particular checks. I condensed and moved the notes about options up. I removed the 'send_configuration' rake examples as the concept is already introduced in the first Rakefile explanation.
puppet-lint.rc now has it's own section because it's that cool.
Puppet-lint is very helpful for people new to puppet, and I remember at the time I first read it, 'Testing your manifests' threw me for a loop because I didn't yet understand the scope of the tool (By manifests, you mean modules and... repos too right?) For that reason I changed this title to 'Usage', which keeps one from getting distracted interpreting the title and on to the rest of the page.
> Potential README changes

- lib/puppet-lint.rb
- lib/puppet-lint/optparser.rb
- spec/puppet-lint/bin_spec.rb
`linenumber` has been deprecated since v1.0.0, which was released in
Aug 2014. It is time to remove it.
Fixes GH-539
Signed-off-by: Romanos Skiadas <rom.skiad@gmail.com>
> Remove formatting with `linenumber`

- lib/puppet-lint/plugins/check_classes.rb
- spec/puppet-lint/plugins/check_classes/code_on_top_scope_spec.rb
Code outside class or define blocks should go in different files
according to the puppet guide.
http://docs.puppetlabs.com/guides/style_guide.html#separate-files
Not only that but it can also trigger nasty bugs as mentioned in issue
https://github.com/rodjek/puppet-lint/issues/220
> Checks for code outside class/define block

- lib/puppet-lint/lexer.rb
Link to reference point inside puppet code where reserved words are maintained.
Ordered keywords to match order in puppet, for easier comparison.
Add tokens for Application Management, to be integrated later.
> True up reserved keywords

- lib/puppet-lint/data.rb
If a new set of tokens is assigned to a PuppetLint::Data instance the @node_indexes cache should be flushed too, alike @class_indexes or @defined_type_indexes.
> @node_indexes should be reset too.

- lib/puppet-lint/lexer.rb
- spec/puppet-lint/lexer_spec.rb
Updates the regexp for the `:TYPE` token so that it is anchored at the end with a word boundary, allowing it to match `Regexp` but not `Regexp_foo` for example.
Fixes #566
> Anchor the end of the :TYPE token regexp

- lib/puppet-lint/data.rb
- spec/fixtures/test/manifests/mismatched_control_comment.pp
- spec/puppet-lint/bin_spec.rb
As reported in #509. If puppet-lint encounters a `lint:endignore` comment that it can't match to `lint:ignore:<check>` comment, it currently throws an exception and dies with a stack trace printed out. This change instead makes it print a friendly warning to the user and then continue on.
Fixes #509
> Handle mismatched control comments gracefully

- lib/puppet-lint/lexer.rb
- spec/puppet-lint/plugins/check_strings/variables_not_enclosed_spec.rb
- spec/puppet-lint/plugins/check_variables/variable_contains_dash_spec.rb
Reimplementation of #500 (which was reverted in #535).
Unlike #500 which removed the ability to parse variable names with dashes, this PR simply changes the regexps that parse the variable names so that they can no longer end with a dash. This allows puppet-lint to correctly detect dash delimited variables (and fix when unenclosed) without creating the false positive from `variable_contains_dash` reported in #504.
Fixes #504
> Reimplementation of --fix support for unenclosed variables delimited by dashes

- lib/puppet-lint/data.rb
- lib/puppet-lint/lexer.rb
- spec/puppet-lint/lexer_spec.rb
The puppet line lexer did not count the newlines in strings. Therefore the tokens have have wrong line number in it. The resulting token read alike this.
```ruby
<Token :SSTRING (test
test) @57:14>
<Token :COMMA (,) @57:24>
```
The error probably was introduced in af3bf4efe71e0b41ffeffa02f1d6185605ba98e8
Even the spec was tweaked to succeed. https://github.com/rodjek/puppet-lint/commit/af3bf4efe71e0b41ffeffa02f1d6185605ba98e8#diff-b9067ea740718189d4de3474b711dba5R21
> Multi line strings

- .gitignore
I tend to create .pp files with manifests from issues for testing. This prevents .pp files in other directories (like `spec/fixtures/test/manifests`) from being ignored, though.
> Ignore *.pp files at the top level

- lib/puppet-lint/plugins/check_classes.rb
- spec/puppet-lint/plugins/check_classes/parameter_order_spec.rb
> (#544, #537) Skip hash contents when checking optional parameters

- lib/puppet-lint/lexer.rb
- spec/puppet-lint/lexer_spec.rb
Fixes #517 
I am not aware of other tokens besides `if`/`elsif` that are permitted and not currently allowed. Please let me know if there are.
> (#517) Update the allowed tokens prior to a regex

- CHANGELOG.md
- README.md
- lib/puppet-lint/version.rb
Prepare for puppet-lint 2.0.0. See #610 for the punchlist.
> 2.1.0 Release

- lib/puppet-lint/plugins/check_classes.rb
- spec/puppet-lint/plugins/check_classes/variable_scope_spec.rb
Multiple variables can now be assigned by using an array on the left hand side of an operation, e.g.
```puppet
[$foo, $bar] = split('baz qux', ' ')
```
This PR changes the logic for the `variable_scope` check so that when it encounters such a case, all the variable names in the array are marked as being in scope.
Fixes #550
> Support array of variables on left side of an assign operation

- lib/puppet-lint/plugins/check_whitespace.rb
- spec/puppet-lint/plugins/check_whitespace/arrow_alignment_spec.rb
This changes the logic used in the `arrow_alignment` check to determine the correct column number for each `=>`. Previously, this was calculated by finding the previous `:INDENT` token and using the length of this token plus all the parameter tokens to determine the correct column to put the arrows in.
Unfortunately, this approach causes [false positives](https://github.com/rodjek/puppet-lint/issue/333) for people who put their opening braces on the same line as their first key-value:
```
{ foo => bar,
baz => qux }
```
The new logic works similarly to the old way, except instead of using the previous `:INDENT` token, we now use the column number of the first parameter token in the block as the base value.
Fixes #333
> Calculate arrow column from first parameter position, not the start of the line

- lib/puppet-lint/lexer.rb
- lib/puppet-lint/plugins/check_whitespace.rb
- spec/puppet-lint/lexer_spec.rb
- spec/puppet-lint/plugins/check_whitespace/arrow_alignment_spec.rb
This PR fixes two bugs that were preventing correct arrow_alignment check results when processing hashes that used strings containing variables as keys. First, the tokeniser's internal state that keeps track of the column number wasn't being updated to take into account the enclosing `${}` characters around variables inside double quoted strings. Secondly, when calculating the correct column number for the arrows, we were only looking at the single token before the arrow, which didn't work for double quoted strings as they are represented by a series of tokens.
Fixes #416 
Fixes #424
> Correctly handle strings-with-variables as hash keys in arrow_alignment check

- spec/spec_helper.rb
Tests for a plugin was not passing because of this error:
```
/var/lib/gems/2.3.0/gems/puppet-lint-2.1.1/spec/spec_helper.rb:5:in `require': cannot load such file -- rspec/json_expectations (LoadError)
from /var/lib/gems/2.3.0/gems/puppet-lint-2.1.1/spec/spec_helper.rb:5:in `<top (required)>'
from /var/lib/gems/2.3.0/gems/puppet-lint-2.1.1/lib/puppet-lint/plugins.rb:28:in `load'
from /var/lib/gems/2.3.0/gems/puppet-lint-2.1.1/lib/puppet-lint/plugins.rb:28:in `load_spec_helper'
from /home/damoreno/playground/git/damoreno-lint/spec/spec_helper.rb:8:in `<top (required)>'
from /home/damoreno/playground/git/damoreno-lint/spec/puppet-lint/plugins/check_version_comparison/version_comparison_spec.rb:1:in `require'
from /home/damoreno/playground/git/damoreno-lint/spec/puppet-lint/plugins/check_vers …
```
> Add LoadError to fix broken tests

- lib/puppet-lint/lexer.rb
- spec/puppet-lint/plugins/check_classes/variable_scope_spec.rb
String interpolations ("${}") can contain a function-call expression, in which case puppet-lint misrecognizes the function name as a top-scope variable.
```
class test {
"${lookup('foo::bar')}"  # lookup is a function but not a variable
}
```
This patch fixes #635
> Correctly handle function calls inside string interpolation

- lib/puppet-lint/plugins/check_classes.rb
- spec/puppet-lint/plugins/check_classes/variable_scope_spec.rb
This patch is a follow-up for #617 and makes the variable_scope checker support multiple variables assignment for nested arrays, such as:
```pp
[$a, [$b, $c]] = [1, [2, 3]]
```
> Support for nested multiple-variable assignments

- lib/puppet-lint/plugins/check_classes.rb
- lib/puppet-lint/plugins/check_resources.rb
- lib/puppet-lint/plugins/check_strings.rb
- lib/puppet-lint/plugins/check_variables.rb
This is a breaking change, scheduled for v3.0.0.
> Plugin review; disable unnecessary plugins

- lib/puppet-lint/lexer.rb
- lib/puppet-lint/plugins/check_resources.rb
- spec/puppet-lint/lexer_spec.rb
- spec/puppet-lint/plugins/check_resources/file_mode_spec.rb
- spec/puppet-lint/plugins/check_resources/unquoted_file_mode_spec.rb
Currently, when the tokeniser hits a function call like `lookup('foo')`, it splits it into a series of tokens like `:NAME`, `:LPAREN`, `:SSTRING`, `:RPAREN`. While this is technically correct, it makes it harder for us to differentiate between an unquoted string and a function name when examining the tokenised file.
My proposed change introduces a new `:FUNCTION_NAME` token type, which is evaluated before `:NAME` token regex and simply checks if this value is followed immediately by an `:LPAREN`.
As a result of this change, we can fix issues like #634 without having add any corner cases to the check logic.
Fixes #634
> Update the tokeniser to differentiate between unquoted strings and function names

- lib/puppet-lint/checkplugin.rb
- lib/puppet-lint/plugins/check_nodes.rb
- spec/puppet-lint/plugins/check_nodes/unquoted_node_name_spec.rb
While the ideal solution is to make use of the syntax validation built into Puppet and will be coming in a future puppet-lint release, this is a temporary stop gap to prevent puppet-lint from crashing and throwing a nasty stack trace to the user when it encounters a node block without the requisite braces.
Fixes #582
> Prevent incomplete node blocks from crashing puppet-lint

- lib/puppet-lint/data.rb
- spec/fixtures/test/manifests/unterminated_control_comment.pp
- spec/puppet-lint/bin_spec.rb
For cases like #622 where an incorrect comment was used to close out an ignored block of code; rather than silently failing to set up the ignore, print a warning so that the user knows that its not working.
Fixes #622
> Warn when control comment blocks are not properly terminated

- appveyor.yml
- spec/puppet-lint/bin_spec.rb
Add appveyor.yml that tests on the same rubies as travis.
Small fix to one test to allow a full path to start with a drive letter as well as /
You can see these tests passing here:
https://ci.appveyor.com/project/james-stocks/puppet-lint/build/1.0.5
I do not have permissions to enable appveyor on this repo.
> (SDK-115) Enable appveyor testing

- spec/spec_helper.rb
When the expected problem is not at the same line number as the actual one, the message displayed is:
`expected that the problem` 
with no further info.
Same happens if `reason` is not the expected one, when `with_reason` is used
> Fix showing of a failure

- lib/puppet-lint/lexer.rb
- spec/puppet-lint/lexer_spec.rb
As exposed in #645, the tokeniser wasn't properly handling regexps when they were used as the first argument in a function (second, third, ... nth worked fine, just not first). When this case was encountered, the regexp would be split into all its component tokens causing very unexpected results (especially if the regexp contained a colon).
Fixes #645
> Allow regexps to used as function arguments

- lib/puppet-lint/checks.rb
If an exception bubbles all the way up to here, catch it, ask the user to open an issue on the project and print out all the debug information needed to recreate the problem so that the user can just copy and paste it into the issue.
> Catch unhandled exception and provide debug info for issue

- lib/puppet-lint/plugins/check_whitespace.rb
- spec/puppet-lint/plugins/check_whitespace/arrow_alignment_spec.rb
When calculating the expected column for the `=>`s to be placed, we split the tokens into a stack of `{ }` delimited blocks. Previously we assumed that blocks of the same depth would have same amount of indentation, e.g.
```
class foo { # move to depth 1
$foo = { # move to depth 2
bar => baz,
} # move to depth 1
$something = { # move to depth 2
this => value,
} # move to depth 1
} # move to depth 0
```
Unfortunately for this assumption, with more complex data structures you can easily have identical depths with different indentation levels, e.g.
```
$my_hash = {
value_1 => {
foo => bar, # depth 2
},
value_2 => [
{
foo => bar, # also depth 2 but indented by two additional spaces
}
]
}
```
This PR changes the logic of the check slightly so that we now clear the expected parameter column for …
> Clear expected parameter column after processing each block when checking arrow alignment

- appveyor.yml
The previous appveyor.yml copied the Ruby versions that travis tests on.
However, appveyor only supports a limited number of ruby versions ( https://www.appveyor.com/docs/build-environment/ )
This wasn't immediately obvious because appveyor defaults to Ruby 1.9.3 then passes tests rather than failing.
This commit changes to only Ruby versions provided by appveyor.
> Restrict appveyor testing to Ruby versions that appveyor supports

- lib/puppet-lint/lexer.rb
- spec/puppet-lint/lexer_spec.rb
Somewhat confusing title, but basically adds support for doing things like `"foo ${join($array, "\n")}"`. Previously, when we detected a `"` character, we would scan up to the next `"` and then pass everything between off to `PuppetLint::Lexer#interpolate_string`. As the Puppet language now supports doing things like the afore mentioned example, this logic needed to change. Through the new `slurp_string` method, we are now a bit more clever about how we scan for the end of the string. If we detect a `${`, we stop looking for `"` until we've found the `}` to close out the interpolated value.
Fixes #516
> Support double quoted strings inside interpolated values in double quoted strings

- lib/puppet-lint/lexer/token.rb
- lib/puppet-lint/plugins/check_resources.rb
- spec/puppet-lint/plugins/check_resources/ensure_first_param_spec.rb
Previously, the fix method for the `ensure_first_param` check looked for the first `:COMMA` or `:SEMIC` token after the ensure param name to find the end of the parameter value, which works for most cases, but not when the value of the ensure parameter is a selector.
This PR fixes this behaviour by adding a `next_token_of` method to `PuppetLint::Lexer::Token` that encapsulates the logic of finding the next token of a certain type (and optionally value) with smarts to skip over blocks. Similarly, a `prev_token_of` method also now exists. These two methods resolve #660 and we can later refactor a lot of the puppet-lint codebase to use these methods and simplify the code a lot.
Fixes #659 & #660
> Fix ensure_first_param fix method to retrieve the full value of the ensure parameter

- lib/puppet-lint/data.rb
- lib/puppet-lint/plugins/check_whitespace.rb
- spec/puppet-lint/plugins/check_whitespace/arrow_alignment_spec.rb
#506 ended up having two different issues in it, both related to the arrow_alignment check but distinct.
```
class example (
$external_ip_base,
) {
bar { 'xxxxxxxxxxx':
inputs => {
'ny' => {
"${external_ip_base}.16:443 ${a} ${b} ${c}" => 'foo',
'veryveryverylongstring8:443'=>'foo',
'simple'=>'foo',
'3'=> :foo,
:baz=> :qux,
3=> 3,
},
},
}
}
```
Here, the problem was due to the use of colons in the hash. Not good syntax wise, but still shouldn't be behaving as it was. This was caused by how `PuppetLint::Data.resource_indexes` was splitting up the token array into groups of tokens for each resource. We were looking for `:COLON` tokens as the start of the resource, which *shouldn't* appear anywhere else inside the resource, but in this case did. So this resource was actually being split up …
> Fix for arrow_alignment bugs in #506

- lib/puppet-lint/lexer.rb
- lib/puppet-lint/lexer/token.rb
- spec/puppet-lint/lexer_spec.rb
Puppet's language allows you to use an unnecessary `$` in enclosed variables e.g. `${$foo}`. At the moment due to the way our lexer works, this extra `$` is removed when run in fix mode without displaying a warning to the user (as reported in #655).
This PR is a bit unusual in that it removes the code that automatically fixes this issue. I've chosen to do this because the style guide doesn't currently mention this case, so I'm going to open issues to update the style guide and also add this as a separate check to puppet-lint.
Fixes #655
> Don't silently remove unnecessary $ from enclosed variables

- lib/puppet-lint/data.rb
- spec/puppet-lint/plugins/check_resources/file_mode_spec.rb
- spec/puppet-lint/plugins/check_resources/unquoted_file_mode_spec.rb
Merges the changes from #666 with the tests from #667 into one PR
/cc @paran1 @rothsa
> Ignore selectors when finding resource type

- lib/puppet-lint/plugins/check_classes.rb
- spec/puppet-lint/plugins/check_classes/arrow_on_right_operand_line_spec.rb
According to [style guide](https://docs.puppet.com/guides/style_guide.html#chaining-arrow-syntax)
> A chain operator should appear on the same line as its right-hand operand.
> Check that arrow is on the line of right operand

- lib/puppet-lint/data.rb
- lib/puppet-lint/plugins/check_whitespace.rb
- spec/puppet-lint/plugins/check_whitespace/arrow_alignment_spec.rb
Handle the case where a `{ }` block can exist that has no `=>` in it, but blocks inside that block do (basically only for case statements). `level_tokens` gets initialised when the first `=>` is encountered in the block.
This PR fixes this behaviour by checking if level_tokens[n] is nil and defaulting it to an empty array. Additionally, the behaviour of `PuppetLint::Data#resource_indexes` was inadvertently changed when I missed a call to `type` which resulted in comparing a `PuppetLint::Lexer::Token` object to a symbol.
Fixes #681
> level_tokens[0] can be nil if there is no params in the top level block

- lib/puppet-lint/plugins/check_classes.rb
Ideally, we would have helper methods to insert and remove tokens that abstracts all this away, but until we do we have to ensure that any `fix` method restores the `next_token` and `prev_token` links after adding or removing tokens from the tokens array.
Fixes #680
> restore the links between tokens after arrow_on_right_operand_line#fix

- README.md
- lib/puppet-lint/tasks/puppet-lint.rb
It's already possible to configure the file glob pattern with:
```ruby
PuppetLint::RakeTask.new :lint do |config|
config.pattern = 'modules'
end
```
This change adds support to the rake test for the alternate
configuration style using `PuppetLint.configuration.*`:
```ruby
PuppetLint.configuration.pattern = 'modules'
```
> Add pattern support to rake task

- README.md
These changes fix minor formatting, whitespace, example and consistency issues, as well as one specific markup syntax error causing <code>``` ruby</code> to show up in the rendered output.
> Readme formatting fixes

- lib/puppet-lint/optparser.rb
- lib/puppet-lint/plugins.rb
We maintain our list of gems by versioning many of them with git SHAs, e.g. "2.2.1.abcdef". However the "prerelease" filter in `Gem::Specification.latest_specs` will filter out any gems that have a letter in their name.
This PR adds the "true" parameter so that all of the gems are loaded. Note that this could be a breaking change if someone is relying on the "prerelease" filtering logic and is not having plugins loaded as a result.
> Permit puppet-lint to load "prerelease" gems

- lib/puppet-lint/lexer.rb
- spec/puppet-lint/lexer_spec.rb
I've added rspec tests to help illustrate the issue that was reported in #697 and #698, which appears to be a failure in `PuppetLint.Lexer.tokenise`.  These tests should pass, but are currently failing due to the regression.
Test cases around line 110 of `lexer_spec.rb` show that the `interpolate_string` method appears to be working (https://github.com/rodjek/puppet-lint/blob/master/spec/puppet-lint/lexer_spec.rb#L110), but adding similar tests for the `tokenise` method do not.  They fail with an incorrect column number if there is a string after the variable. e.g. `  "${foo}bar" =>`
> Take into account length of DQPOST token when updating column number

- lib/puppet-lint.rb
- lib/puppet-lint/checks.rb
- lib/puppet-lint/lexer.rb
- spec/puppet-lint/bin_spec.rb
- spec/puppet-lint/lexer_spec.rb
Catch unterminated double quoted strings and raise a LexerError (with a meaningful reason). Also, adjusted how the LexerErrors are displayed to accommodate these reasons when present by moving the "Try running puppet parser validate" message to STDERR
Fixes #727
> Improve handling of unterminated double quoted strings

- lib/puppet-lint.rb
Force reading the manifest files with the UTF-8 encoding.
Fixes #693 
Fixes #729
> Read the manifest files as UTF-8

- lib/puppet-lint.rb
- lib/puppet-lint/configuration.rb
- spec/puppet-lint/configuration_spec.rb
As raised in #714, puppet-lint fails hard when it encounters an SE Linux policy package (which unfortunately also uses the `.pp` extension).
This change clears out the read manifest data if the first 4 bytes of the file are 0xF97CFF8F (as defined in the policy package file format), which effectively makes puppet-lint silently skip over these files.
Additionally, as brought up in the same issue, puppet-lint now sets the default ignore_paths to include `vendor/**/*.pp` for a nicer default experience for bundler users.
Fixes #714
> Handle SE Linux policy package files

- lib/puppet-lint/data.rb
- spec/puppet-lint/ignore_overrides_spec.rb
The original implementation was flawed because the second capture group in the
regex would be overwritten with the value of the last control comment. Instead
of trying to do it all in one pattern, we now split the comment into words and
parse each one seperately.
Fixes #726
> Split control comments into words before parsing

- lib/puppet-lint/checkplugin.rb
- lib/puppet-lint/data.rb
- lib/puppet-lint/plugins/check_classes/arrow_on_right_operand_line.rb
- lib/puppet-lint/plugins/check_comments/star_comments.rb
- lib/puppet-lint/plugins/check_strings/only_variable_string.rb
- spec/puppet-lint/data_spec.rb
This make it easier to implement `fix` in plugins, without the risk of breaking puppet-lint (see #684 for ref)
Also it adds tests that the links are maintained, which is not covered by the current specs
> Add helper methods to add and remove tokens while maintaining the token links

- lib/puppet-lint/plugins/check_classes/autoloader_layout.rb
- lib/puppet-lint/plugins/check_classes/class_inherits_from_params_class.rb
- lib/puppet-lint/plugins/check_classes/inherits_across_namespaces.rb
- lib/puppet-lint/plugins/check_classes/names_containing_dash.rb
- lib/puppet-lint/plugins/check_classes/parameter_order.rb
- lib/puppet-lint/plugins/check_conditionals/selector_inside_resource.rb
- lib/puppet-lint/plugins/check_documentation/documentation.rb
- lib/puppet-lint/plugins/check_nodes/unquoted_node_name.rb
- spec/puppet-lint/plugins/check_classes/names_containing_dash_spec.rb
Mostly applied early returns to lower the nesting level.
In some cases extracted helper methods to make the code more obvious.
> Plugins: Improve code readability

- lib/puppet-lint/checkplugin.rb
- lib/puppet-lint/checks.rb
- lib/puppet-lint/lexer.rb
- spec/spec_helper.rb
This mostly converts hashes to 1.9 style (following #647) and also makes some minor code style corrections (in a separate commit)
> Code style improvements

- lib/puppet-lint/lexer.rb
- lib/puppet-lint/lexer/token.rb
- spec/puppet-lint/lexer_spec.rb
Changes how the `${}` characters that enclose interpolated values are rendered. Instead of adding them when rendering the variable tokens to manifest, they are now rendered as part of the surrounding string or heredoc tokens.
Fixes #703
> Render the ${} enclosures as part of the string tokens

- lib/puppet-lint/bin.rb
- spec/puppet-lint/bin_spec.rb
This will prevent Ruby from changing the line endings depending on the platform puppet-lint is running on when writing the fixed manifest.
Fixes #748
> Open manifest as binary when writing fixed manifest

- lib/puppet-lint/plugins/check_classes/arrow_on_right_operand_line.rb
- spec/puppet-lint/plugins/check_classes/arrow_on_right_operand_line_spec.rb
Build the proper chain of tokens for the appropriate placement of the arrow chain, indents, and linefeeds
Fixes #695
#puppethack
> Chaining arrow syntax fix introduces trailing whitespaces

- spec/puppet-lint/configuration_spec.rb
This part of the method_missing code path was not tested before, leading to the issues in the 2.3.1 release (fixed in #755). This new test (tested by reverting locally to 2.3.1 and confirmed that it does recreate the issue) will prevent a similar regression from going unnoticed in the future.
> Add spec for issue raised in #754 #756

- lib/puppet-lint/tasks/puppet-lint.rb
In #733, `ignore_paths` was given the default value of `['vendor/**/*.pp']`, which unfortunately overrides the `ignore_paths` value given to the rake task via the yielded block.
```ruby
PuppetLint::RakeTask.new(:lint) do |config|
config.ignore_paths = ['some', 'paths']
end
```
This change will make it so that if the rake task is configured in this fashion, the default value is only applied if the user hasn't supplied their own `ignore_paths` value.
Fixes #760
> Don't override ignore_paths set in rake task with default value

- lib/puppet-lint.rb
PuppetLink#log_format checks that configuration.log_format == '', but in
fact it receives nil. So nil is not equal ''. No default configuration
is set as result and we get an error in PuppetLint#format_message about
no method % for nil.
This commit fixes it by checking that value is nil? or empty? which is
proper way to determine absent value for configuration.log_format.
- https://github.com/rodjek/puppet-lint/issues/756
> Fix setup of default log_format in PuppetLink.configuration when it is empty.

- .gitignore
- .travis.yml
- Rakefile
- appveyor.yml
- lib/puppet-lint/tasks/release_test.rb
In order to hopefully avoid bad releases like 2.3.1, this adds some basic acceptance tests that should run on PRs that create new releases (branch named like `2_3_3_release`).
> Add some basic acceptance tests

- lib/puppet-lint/tasks/release_test.rb
Open3 on Ruby 1.8.7 doesn't have a `capture2e` method. Actually, it doesn't have anything but `popen3`.
> Change acceptance tests to work with Ruby 1.8.7

- lib/puppet-lint/bin.rb
- spec/puppet-lint/bin_spec.rb
`Dir.glob` does not support backslash separated paths (because backslash is used as an escape character), so if puppet-lint is running on a platform where `File::ALT_SEPARATOR` is defined, substitute any occurrence of it in the path argument with `File::SEPARATOR` before passing the path to `Dir.glob`.
> Add support for passing backslash separated paths to puppet-lint

- README.md
- lib/puppet-lint/plugins/check_classes/arrow_on_right_operand_line.rb
- lib/puppet-lint/plugins/check_classes/autoloader_layout.rb
- lib/puppet-lint/plugins/check_classes/inherits_across_namespaces.rb
- lib/puppet-lint/plugins/check_classes/names_containing_uppercase.rb
- lib/puppet-lint/plugins/check_classes/nested_classes_or_defines.rb
- lib/puppet-lint/plugins/check_classes/parameter_order.rb
- lib/puppet-lint/plugins/check_classes/right_to_left_relationship.rb
- lib/puppet-lint/plugins/check_classes/variable_scope.rb
- lib/puppet-lint/plugins/check_comments/slash_comments.rb
- lib/puppet-lint/plugins/check_comments/star_comments.rb
- lib/puppet-lint/plugins/check_conditionals/case_without_default.rb
- lib/puppet-lint/plugins/check_conditionals/selector_inside_resource.rb
- lib/puppet-lint/plugins/check_documentation/documentation.rb
- lib/puppet-lint/plugins/check_resources/ensure_first_param.rb
- lib/puppet-lint/plugins/check_resources/ensure_not_symlink_target.rb
- lib/puppet-lint/plugins/check_resources/file_mode.rb
- lib/puppet-lint/plugins/check_resources/unquoted_file_mode.rb
- lib/puppet-lint/plugins/check_resources/unquoted_resource_title.rb
- lib/puppet-lint/plugins/check_strings/double_quoted_strings.rb
- lib/puppet-lint/plugins/check_strings/only_variable_string.rb
- lib/puppet-lint/plugins/check_strings/single_quote_string_with_variables.rb
- lib/puppet-lint/plugins/check_strings/variables_not_enclosed.rb
- lib/puppet-lint/plugins/check_whitespace/140chars.rb
- lib/puppet-lint/plugins/check_whitespace/2sp_soft_tabs.rb
- lib/puppet-lint/plugins/check_whitespace/80chars.rb
- lib/puppet-lint/plugins/check_whitespace/arrow_alignment.rb
- lib/puppet-lint/plugins/check_whitespace/hard_tabs.rb
- lib/puppet-lint/plugins/check_whitespace/trailing_whitespace.rb
Current versions of the documentation were migrated from docs.puppet.com to puppet.com/docs at PuppetConf this year. There are redirects in place, but having the correct link is preferred. In this PR I've updated all docs URLs to point to the correct locations.
> (maint)(docs) Update docs URLs post-migration

- lib/puppet-lint/tasks/puppet-lint.rb
The value of `PuppetLint.configuration.ignore_paths` was ignored,
as described in issue #774
> Fix setting ignore_paths in Rake task

- lib/puppet-lint.rb
- lib/puppet-lint/lexer.rb
- spec/puppet-lint/lexer_spec.rb
Previously, when tokenising the manifest, the value of single line comment tokens would include the line ending. Unfortunately, when the file has Windows style line endings (`\r\n`) and is read in as binary (which skips line ending conversion) and the tested on a host using Unix style line endings it would get tokenised as the following, throwing off the line number calculations:
```
<Token :COMMENT (" foo\r")>
<Token :NEWLINE ("\n")>
```
With this change, the `:COMMENT` and `:SLASH_COMMENT` tokens no longer include the line endings, instead they are their own tokens.
```
<Token :COMMENT (" foo")>
<Token :NEWLINE ("\r\n")>
```
Fixes #778
> (#778) Don't include line ending in single line comment token values

- lib/puppet-lint.rb
- lib/puppet-lint/checks.rb
- lib/puppet-lint/data.rb
- spec/puppet-lint/data_spec.rb
For example:
```
class foo:bar {
}
```
Fixes #801
> Handle single colon in resource name syntax error

- lib/puppet-lint/bin.rb
- lib/puppet-lint/optparser.rb
- spec/puppet-lint/bin_spec.rb
- define `--ignore-paths` option in optparser
- in `bin.rb` skip paths that match any pattern in `ignore_paths`
- as a consequence this also means ignore_paths will get loaded from .puppet-lint.rc, if any
> Allow passing ignore_paths from cli

- Rakefile
- lib/puppet-lint/optparser.rb
- lib/puppet-lint/tasks/gemfile_rewrite.rb
- lib/puppet-lint/tasks/release_test.rb
Makes the argument to `PuppetLint::OptParser.build` optional in order to not introduce a breaking API change (the solution in #811 would work, but would have just worked around the breaking change).
Also, this PR updates the `release_test` rake task that runs before each release is tagged so that it now runs puppet-lint via the rake task (in addition to running it via the CLI as it does currently) so that we don't publish a broken rake task again.
Replaces #811 
Fixes #812
> Make PuppetLint::OptParser.build argument optional

- lib/puppet-lint/checks.rb
Depending on the value of `LANG` and `LC_COLLATE`, the check plugins can be loaded (and therefore registered and run) in different orders on different hosts. This lead to scenarios where the `arrow_on_right_operand_line` would run and mutate the `tokens` array to fix problems before all the data structures in `PuppetLint::Data`were fully populated.
This PR changes the check running logic so that all of the checks are run before any of the detected problems are fixed.
Fixes #776 
Fixes #781 
Fixes #799
> Run all the checks before fixing problems

- lib/puppet-lint/plugins/check_whitespace/trailing_whitespace.rb
The main issue was fixed in #815 (ordering the fixing to happen after all the checks have finished), but it also exposed that I wasn't checking the value of the token passed to the fix method for the `trailing_whitespace` check, so this PR fixes that.
Fixes #798
> Check if token still exists before fixing trailing_whitespace

- lib/puppet-lint/plugins/check_classes/arrow_on_right_operand_line.rb
- spec/puppet-lint/plugins/check_classes/arrow_on_right_operand_line_spec.rb
The previous behaviour of this fix was far too aggressive. It would remove all the tokens between the two operands and then recreate them, which resulted in any comments between the two operands also being removed from the fixed manifest.
This PR changes the logic so that it simply moves the arrow token to before the right operand and trims any trailing whitespace it created by doing so.
Fixes #792
> Less aggressive fix method for arrow_on_right_operand_line

- lib/puppet-lint/plugins/check_resources/ensure_first_param.rb
- spec/puppet-lint/plugins/check_resources/ensure_first_param_spec.rb
If an ensure statement is defined within a hash inside a resource, then
ensure_param_name_token will end up being set to nil. This is because
first_param_comma_token jumps to the comma that ends the hash.
This is valid puppet syntax, so the linter shouldn't error out.  With
puppet default arguments, it is normal to pass a hash to a class, which
are applied with the * operator, and ensure could be one of the
arguments. For that reason, moving the ensure out of the inner hash will
change the semantics of the code. Instead, just raise a NoFix and the
user will see the warning.
> Resource: fix nested ensure error.

- lib/puppet-lint/lexer.rb
- spec/puppet-lint/lexer_spec.rb
Currently, the parser will fail if there is a space in the heredoc tag. This PR updates the heredoc regex to allow for white spaces in the heredoc tag.  With this PR, `@("MYVAR" /)` no longer causes the following error.
file contents:
```
class testing {
$myvar = @("MYVAR" /)
Some string
in a heredoc
| MYVAR
notice($myvar)
}
```
error:
```
TypeError: no implicit conversion of nil into String
/Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-lint-2.3.6/lib/puppet-lint/lexer.rb:496:in `initialize'
/Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-lint-2.3.6/lib/puppet-lint/lexer.rb:496:in `new'
/Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puppet-lint-2.3.6/lib/puppet-lint/lexer.rb:496:in `interpolate_heredoc' …
```
> Allow for spaces in the heredoc tag

- lib/puppet-lint/lexer.rb
- spec/puppet-lint/lexer_spec.rb
Updates the lexer to recognize multiline regexes.  Updates the unit tests to expect and test for that behavior.
Resolves #833
> Recognizes multiline regexes

- lib/puppet-lint/lexer.rb
For some reason using a lookahead assertion for the opening parenthesis
after a function name is much faster for large manifests. The old
version shows some pathologic behaviour and becomes very slow for
manifests with many entries -- as described in #717.
I don't understand why the old version behaves badly. I was able to
reproduce the speedup with Ruby 1.9.3 as well as with 2.3.something.
> Use lookahead assertion for matching function name

- lib/puppet-lint/data.rb
- spec/puppet-lint/data_spec.rb
> Avoid internal error for typoed namespace

- lib/puppet-lint/plugins/check_strings/quoted_booleans.rb
The style guide has been updated since this check was written so that
quoted booleans are no longer a warning.
Closes #474
Closes #844
> Disable quoted_booleans check by default

- lib/puppet-lint/lexer/token.rb
Rather than throwing an unhandled exception.
Fixes #740
> Report syntax error on unbalanced braces

- lib/puppet-lint/plugins/check_strings/variables_not_enclosed.rb
- spec/puppet-lint/plugins/check_strings/variables_not_enclosed_spec.rb
```
$ cat test.pp
$foo = "/path/$files['some']"
$ bin/puppet-lint -f test.pp
FIXED: variable not enclosed in {} on line 1
$ cat test.pp
$foo = "/path/${files['some']}"
```
Fixes #826
> Include hash/array references when enclosing variables

- lib/puppet-lint/optparser.rb
- spec/fixtures/test/manifests/two_warnings.pp
- spec/puppet-lint/bin_spec.rb
Arguments given on the command line should override those from
config files. That implies that config files must be read first.
Only peeking into the command line args can show if config files
should be used at all.
This change might break existing setups.
Fixes #879.
> Let command line args override config from files

- lib/puppet-lint/lexer.rb
- lib/puppet-lint/lexer/string_slurper.rb
- spec/puppet-lint/lexer/string_slurper_spec.rb
Fixes #885 
I think this will also fix #886 but I don't have enough info to accurately reproduce the problem yet.
> Fix escaped ${} enclosure handling when slurping double quoted strings

- lib/puppet-lint/lexer.rb
- spec/puppet-lint/plugins/check_classes/variable_scope_spec.rb
In earlier Puppet version it wasn't possible to assign a regex to
a variable. This has changed somewhere around version 3.5 and regexes
are valid rvalues now. Compare
https://tickets.puppetlabs.com/browse/PUP-1074
> Allow parsing of regexes as rvalues

- lib/puppet-lint/lexer/string_slurper.rb
- spec/puppet-lint/lexer/string_slurper_spec.rb
Since the ESC_DQUOTE_PATTERN accepts any positive number of
backslashes before the double quote, we have to look for
the end of string first.
This should help with issue #891.
> Search end of string before assuming escaped quote

- .rubocop_todo.yml
- lib/puppet-lint/data.rb
By ignoring the already analysed tokens the index operations
on the tokens array become substantially faster for large
manifests. This should solve issue #717.
> Speed up calculation of resource indexes

- lib/puppet-lint/plugins/check_resources/ensure_first_param.rb
Currently the fix method for this check relies upon the position of the
first parameter in the tokens array to operate which is determined when
the manifest is first loaded. If checks with fix methods that add or
remove tokens (like the `trailing_whitespace` check) run before this
check, the saved position becomes no longer accurate causing the fix
method to fail.
Fixes #906
Fixes #905
Fixes #839
> Do not rely on tokens array positioning when fixing ensure_first_param problems

- lib/puppet-lint/lexer.rb
- lib/puppet-lint/lexer/string_slurper.rb
- spec/puppet-lint/lexer/string_slurper_spec.rb
Otherwise the lexer will skip over too many characters after slurping
a double quoted string (or heredoc) that contains multibyte characters.
Fixes #912
> (#912) Count consumed chars not bytes when slurping strings

- plugins/index.md
Warn for uses of racist terms that you may want to stop using:master/slave, whitelist/blacklist.  (Take 2)
> racism_terminology plugin

- plugins/index.md
I'm writing my own linter to enforce a number of (opinionated) whitespace rules, such as newline placement, number of spaces between/after certain keywords.
I'll be adding more items as I find them in our own manifests.
> Add manifest_whitespace plugin

- lib/puppet-lint/plugins/check_documentation/documentation.rb
- spec/puppet-lint/plugins/check_documentation/documentation_spec.rb
puppet-strings doesn't parse documentation if there is an empty line between the comments and the actual class/define. This enhances the check by only accepting a single newline.
> Disallow empty lines between docs and class/define

- lib/puppet-lint/lexer.rb
- lib/puppet-lint/lexer/token.rb
- spec/puppet-lint/plugins/check_variables/variable_is_lowercase_spec.rb
There's a conflict in the current lexer that where the `type` keyword
token (`:type = :TYPE, :value => 'type'`) conflicts with the known type
name tokens (e.g. `:type => :TYPE, :value => 'Integer'`).
The proper solution to this would be to use a different token type for
these two use cases, but that is a breaking change as the token types
are considered public API for semver purposes. Until the next major
release where this can be introduced, this fix will do.
Fixes #929
> Correctly lex non-keyword type tokens in interpolation

- lib/puppet-lint/tasks/puppet-lint.rb
When using the Rake task with an open glob such as `**/*`, `puppet-lint` will fail to load directories.
> Improve Rake task

- Gemfile
- lib/puppet-lint/plugins/check_classes/parameter_order.rb
- spec/puppet-lint/plugins/check_classes/parameter_order_spec.rb
Class/defined type parameter name tokens can be more accurately selected
based on the type of non-whitespace token that preceeds it.
`:VARIABLE` preceeded by:
* `:LPAREN` - First parameter, no data type
* `:COMMA` - Subsequent parameters, no data type
* `:TYPE` - Parameter with a simple data type (e.g. `String`)
* `:RBRACK` - Parameter with a complex data type (e.g. `Array[String]`)
As before, tokens within balanced pairs of parens will be automatically
skipped over, preventing a function call that takes a variable parameter
from generating a false positive in the first 2 cases.
Fixes #930
> Select parameter tokens based on preceeding code token

- lib/puppet-lint.rb
- spec/puppet-lint/bin_spec.rb
As reported in https://github.com/rodjek/puppet-lint/issues/837 it's
sometimes difficult to identify the check that causes a particular
warning or error output. By including the check name in the log output
it becomes easier to disable checks via control comments or command
line parameters. The old format can be restored with '--log-format'.
> Include check name in log output by default
