rodjek/puppet-lint

lib/puppet-lint/checks.rb
=> Don't suppress nil values in manifest_lines

lib/puppet-lint/data.rb
Gotta love 1.8.7 and making breaking changes in patch versions...
Closes #364
=> Support older 1.8.7 patch numbers Kernel#caller output

lib/puppet-lint/data.rb
Returns an Array of Hashes with the positions of all the function calls
within the tokenised manifest. Each Hash has the following Symbol keys:
* :start -   The Integer position in the `tokens` Array pointing to the
first token of the function call.
* :end -     The Integer position in the `tokens` Array pointing to the
last token of the function call.
* :tokens -  A subset of the `tokens` Array, from the :start to :end
positions.
Returns an Array of Hashes with the positions of all the array values
within the tokenised manifest. Each Hash has the following Symbol:
* :start -   The Integer position in the `tokens` Array pointing to
the first token of the array value.
* :end -     The Integer position in the `tokens` Array pointing to
the last token of the array value.
* :tokens -  A …
=> Add various helper functions

lib/puppet-lint/plugins/check_strings.rb, spec/puppet-lint/plugins/check_strings/puppet_url_without_modules_spec.rb
This is intended to fix issue #390
=> Add the fix functionality to puppet_url_without_modules

checks/140chars/index.md, checks/index.md, controlcomments/index.md
=> Update documentation for 140chars

lib/puppet-lint/plugins/check_whitespace.rb, spec/puppet-lint/plugins/check_whitespace/arrow_alignment_spec.rb
Fixes https://github.com/rodjek/puppet-lint/issues/470
=> Fix arrow aligment check in multiple resources declaration

lib/puppet-lint/version.rb
Upgrade version to 2.0.0 and publish the new gem version.
=> (GH443) Release 2.0.0 PR

CHANGELOG.md
Created with github_changelog_generator 👍
=> Add fully-detailed CHANGELOG

plugins/index.md
this is a replacement for #449 where I merged the wrong branch.
=> add lint test for resource references

lib/puppet-lint/plugins/check_comments.rb, spec/puppet-lint/plugins/check_comments/star_comments_spec.rb
=> (GH462) Multi-line comments can now be fixed.

lib/puppet-lint/plugins/check_whitespace.rb, spec/puppet-lint/plugins/check_whitespace/arrow_alignment_spec.rb
Related to #424. @TomOnTime looking for your feedback to see if this is what you'd like to see.
=> Add better description of the problem in arrow_alignment check

README.md, lib/puppet-lint/lexer.rb, lib/puppet-lint/plugins/check_variables.rb, spec/puppet-lint/plugins/check_strings/variables_not_enclosed_spec.rb
Reverts rodjek/puppet-lint#500 (see #504)
=> Revert "Bugfix: properly handling $gronk-$grouik with --fix (fix #442)"

CHANGELOG.md, lib/puppet-lint/version.rb
=> Release 2.0.2

lib/puppet-lint/plugins/check_classes.rb, spec/fixtures/test/manifests/ignore_reason.pp, spec/puppet-lint/bin_spec.rb, spec/puppet-lint/plugins/check_classes/code_on_top_scope_spec.rb
Updated `:linenumber` to `:line` and fixed tests
Supersedes #223
=> Updates PR for #223

README.md
=> Include --fix usage instructions

lib/puppet-lint/plugins/check_classes.rb, spec/puppet-lint/plugins/check_classes/name_contains_uppercase_spec.rb
=> Implement a linter for uppercase class names

checks/names_containing_uppercase/index.md
=> Add names_containing_uppercase docs

README.md
=> (#369) Document existence of control comments

lib/puppet-lint/lexer.rb, spec/puppet-lint/lexer_spec.rb
=> (#531) Treat barewords beginning with an underscore as :NAME tokens

plugins/index.md
I've added a small collection of my public puppet-lint plugins to the plugins page. Hopefully some of them will be of use to other people.
=> Add puppet-lint plugins from deanwilson to plugins page

plugins/index.md
=> Documentation on plugin usage.

.travis.yml
=> Test against Ruby 2.4.0

lib/puppet-lint/plugins/check_classes.rb, spec/puppet-lint/plugins/check_classes/variable_scope_spec.rb
Lambdas can be nested, in which case puppet-lint was not able to handle parameter scopes correctly.
=> Correctly handle nested lambdas

lib/puppet-lint/plugins/check_strings.rb, spec/puppet-lint/plugins/check_strings/double_quoted_strings_spec.rb
=> Check for escaped backslashes too

checks/arrow_on_right_operand_line/index.md, checks/index.md
=> Document the arrow_on_right_operand_line check on the website

README.md
=> Note arrow_on_right_operand_line in the README

README.md
=> Document the configuration file better

lib/puppet-lint/lexer.rb, spec/puppet-lint/lexer_spec.rb
=> Handle unicode spaces in the tokeniser

lib/puppet-lint/configuration.rb
=> fix logic in method_missing

developer/tokens/index.md
It was added to puppet-lint in
https://github.com/rodjek/puppet-lint/commit/f13e6ddb974db715d3288990e642a448e1bfedd3
=> Add :FUNCTION_NAME to the token documentation

.rubocop_todo.yml, lib/puppet-lint/bin.rb, lib/puppet-lint/optparser.rb
My proposal to issue #787 
Fixes #787
=> Option to disable loading default configurations files

README.md
Super cool tool! I made a [GitHub Actions action](https://github.com/marketplace/actions/puppet-lint-action) that provides linter feedback in workflows, figured it was worth adding here.
*Description of changes:* Add GitHub Actions action section to README
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> README - Add GitHub Actions action

lib/puppet-lint/plugins/check_conditionals/case_without_default.rb, spec/puppet-lint/plugins/check_conditionals/case_without_default_spec.rb
=> Only look for 'default' at first level of 'case' statement

.rubocop_todo.yml, lib/puppet-lint/data.rb, spec/puppet-lint/plugins/check_resources/ensure_first_param_spec.rb
=> Ignore hash keys when checking resource parameter order

README.md
Should avoid the confusion described in #832.
=> Enhance documentation for configuration file usage

lib/puppet-lint/plugins/check_strings/variables_not_enclosed.rb, spec/puppet-lint/plugins/check_strings/variables_not_enclosed_spec.rb
=> Handle unenclosed variables followed by dashes when fixing

lib/puppet-lint/lexer.rb, spec/puppet-lint/lexer_spec.rb
=> Fix non-indented heredoc parsing

checks/autoloader_layout/index.md
=> Update link to a currently working version

lib/puppet-lint/lexer.rb, spec/puppet-lint/lexer_spec.rb
Test (but no fix) showing issue #897
=> Fix regression in tokenization in double-quoted strings

lib/puppet-lint/lexer/string_slurper.rb, spec/puppet-lint/lexer/string_slurper_spec.rb
=> (#851) Ensure heredoc ending tag is on its own line
